name: Upload component
on:
  workflow_dispatch:

env:
  COMPONENT_NAME: pl_modbus

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Copy supplementary files
        run: |
          cp ./LICENSE ./component/LICENSE
          cp ./README.md ./component/README.md
          cp ./CHANGELOG.md ./component/CHANGELOG.md
          cp -r ./examples ./component/examples

      - name: Rename component directory
        run: 
          mv ./component ./$COMPONENT_NAME

      - name: Upload
        uses: espressif/upload-components-ci-action@v2
        with:
          components: "${{env.COMPONENT_NAME}}"
          namespace: "plasmapper"